-- 1. crearea utilizatorului PE CONEXIUNEA SYS
CREATE USER AGENT_VANZARI IDENTIFIED BY parolaagent123;
GRANT CREATE SESSION TO AGENT_VANZARI;
GRANT UNLIMITED TABLESPACE TO AGENT_VANZARI;

-- Drepturi pe VEDERI
GRANT SELECT ON PRODUS TO AGENT_VANZARI;
GRANT SELECT ON STOC TO AGENT_VANZARI;
GRANT SELECT, INSERT ON CLIENT TO AGENT_VANZARI;
GRANT SELECT, INSERT ON COMANDA_VANZARE TO AGENT_VANZARI;
GRANT SELECT, INSERT ON CV_LINIE TO AGENT_VANZARI;

COMMIT;
